version: '3.7'

services:
  database:
    build:
      context: ./docker-database
      dockerfile: Dockerfile.dev
    image: compass/database
    container_name: compass-uol-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=dev123456
      - POSTGRES_DB=compass_uol
    volumes:
      - pgdata:/data/postgres
    networks:
      - compass-uol

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: compass-uol-node
    depends_on:
      - database
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - compass-uol

volumes:
  pgdata:
    driver: local

networks:
  compass-uol:
    name: compass-uol-network
